# Generated by Django 4.0.3 on 2023-09-08 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MemberPersonal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personal_id', models.CharField(max_length=50, unique=True)),
                ('personal_password', models.CharField(max_length=50)),
                ('personal_name', models.CharField(max_length=50)),
                ('personal_birth', models.CharField(max_length=8)),
                ('personal_email', models.CharField(max_length=50, unique=True)),
                ('personal_phonenum', models.CharField(max_length=50, unique=True)),
                ('personal_address', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'member_personal',
            },
        ),
    ]
