# Generated by Django 4.0.3 on 2023-09-08 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keepwork', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.CharField(max_length=50, unique=True)),
                ('company_password', models.CharField(max_length=50)),
                ('company_manager', models.CharField(max_length=50)),
                ('company_email', models.CharField(max_length=50)),
                ('company_tel', models.CharField(max_length=50, unique=True)),
                ('company_registnum', models.CharField(max_length=12, unique=True)),
                ('company_name', models.CharField(max_length=50)),
                ('representative_name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('establishment_year', models.PositiveIntegerField()),
                ('number_of_employees', models.PositiveIntegerField()),
                ('company_type', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'member_company',
            },
        ),
    ]
