# Generated by Django 4.0.3 on 2023-09-08 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keepwork', '0002_membercompany'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membercompany',
            name='id',
        ),
        migrations.RemoveField(
            model_name='memberpersonal',
            name='id',
        ),
        migrations.AlterField(
            model_name='membercompany',
            name='company_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='memberpersonal',
            name='personal_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, unique=True),
        ),
    ]
