# Generated by Django 4.0.3 on 2023-09-09 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keepwork', '0004_notice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membercompany',
            old_name='address',
            new_name='company_address',
        ),
        migrations.RenameField(
            model_name='membercompany',
            old_name='establishment_year',
            new_name='company_employees',
        ),
        migrations.RenameField(
            model_name='membercompany',
            old_name='number_of_employees',
            new_name='company_establishment',
        ),
        migrations.RenameField(
            model_name='membercompany',
            old_name='company_tel',
            new_name='company_phonenum',
        ),
        migrations.RenameField(
            model_name='membercompany',
            old_name='representative_name',
            new_name='company_representative',
        ),
    ]
