# Generated by Django 4.0.3 on 2023-09-10 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('keepwork', '0005_rename_address_membercompany_company_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('resume_listnum', models.AutoField(primary_key=True, serialize=False)),
                ('resume_title', models.CharField(max_length=50)),
                ('resume_academic', models.CharField(max_length=100)),
                ('resume_career', models.CharField(max_length=100)),
                ('resume_introduction', models.CharField(max_length=500)),
                ('resume_certificate', models.CharField(max_length=100)),
                ('resume_learning', models.CharField(max_length=100)),
                ('resume_desire', models.CharField(max_length=100)),
                ('resume_complete', models.CharField(max_length=10)),
                ('personal_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='keepwork.memberpersonal', unique=True)),
            ],
            options={
                'db_table': 'resume',
            },
        ),
    ]
