# Generated by Django 4.0.3 on 2023-09-10 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keepwork', '0008_job'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='resume_title',
        ),
    ]
