# Generated by Django 4.0.3 on 2023-09-12 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keepwork', '0009_remove_job_resume_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_contact_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_email',
            field=models.CharField(max_length=50),
        ),
    ]
