# Generated by Django 4.0.3 on 2023-09-13 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keepwork', '0010_alter_job_job_contact_number_alter_job_job_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membercompany',
            name='company_employees',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='membercompany',
            name='company_establishment',
            field=models.CharField(max_length=10),
        ),
    ]
