# Generated by Django 4.0.3 on 2023-09-16 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keepwork', '0011_alter_membercompany_company_employees_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Job',
        ),
    ]
