# Generated by Django 4.0.3 on 2023-09-16 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keepwork', '0017_alter_membercompany_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membercompany',
            name='company_name',
            field=models.CharField(default='', max_length=50, unique=True),
        ),
    ]
